<<<<<<< HEAD
# Generated by Django 3.1 on 2020-08-29 05:01
=======
# Generated by Django 3.1 on 2020-08-28 19:49
>>>>>>> 668d4e44acf3333028eee3b1f81f8d2be33889db

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=32)),
                ('image', models.ImageField(blank=True, default='bbt.png', null=True, upload_to='')),
                ('calories', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=32)),
                ('image', models.ImageField(blank=True, default='bbt.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.product')),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
            bases=('menu.product', models.Model),
        ),
        migrations.CreateModel(
            name='MilkTea',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.product')),
                ('isHot', models.BooleanField(default=False)),
                ('toppings', models.ManyToManyField(to='menu.Topping')),
            ],
            bases=('menu.product', models.Model),
        ),
        migrations.CreateModel(
            name='LemonTea',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.product')),
                ('isHot', models.BooleanField(default=False)),
                ('toppings', models.ManyToManyField(to='menu.Topping')),
            ],
            bases=('menu.product', models.Model),
        ),
        migrations.CreateModel(
            name='FreshFruit',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.product')),
                ('isHot', models.BooleanField(default=False)),
                ('toppings', models.ManyToManyField(to='menu.Topping')),
            ],
            bases=('menu.product', models.Model),
        ),
        migrations.CreateModel(
            name='CheeseFoam',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.product')),
                ('isHot', models.BooleanField(default=False)),
                ('toppings', models.ManyToManyField(to='menu.Topping')),
            ],
            bases=('menu.product', models.Model),
        ),
    ]
