# Generated by Django 3.0.8 on 2020-08-03 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=99)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(choices=[('a,', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Product')),
            ],
        ),
    ]
