# Generated by Django 3.1 on 2020-08-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshfruit',
            name='isHot',
        ),
        migrations.RemoveField(
            model_name='freshfruit',
            name='toppings',
        ),
    ]
