# Generated by Django 3.0.8 on 2020-08-03 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200803_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='icedfreshfruit',
            name='sugar',
            field=models.CharField(choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=5),
        ),
        migrations.AlterField(
            model_name='icedfreshfruit',
            name='toppings',
            field=models.CharField(choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=10),
        ),
    ]
