# Generated by Django 3.0.8 on 2020-08-03 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200803_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotcheesefoam',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='hotfreshfruit',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='hotlemontea',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='hotmilktea',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='icedcheesefoam',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='icedfreshfruit',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='icedlemontea',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='icedmilktea',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
    ]
