# Generated by Django 3.0.8 on 2020-08-04 00:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200803_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotcheesefoam',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9),
        ),
        migrations.AlterField(
            model_name='hotcheesefoam',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19),
        ),
        migrations.AlterField(
            model_name='hotfreshfruit',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9),
        ),
        migrations.AlterField(
            model_name='hotfreshfruit',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19),
        ),
        migrations.AlterField(
            model_name='hotlemontea',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9),
        ),
        migrations.AlterField(
            model_name='hotlemontea',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19),
        ),
        migrations.AlterField(
            model_name='hotmilktea',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9),
        ),
        migrations.AlterField(
            model_name='hotmilktea',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19),
        ),
        migrations.AlterField(
            model_name='icedcheesefoam',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9),
        ),
        migrations.AlterField(
            model_name='icedcheesefoam',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19),
        ),
        migrations.AlterField(
            model_name='icedfreshfruit',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9),
        ),
        migrations.AlterField(
            model_name='icedfreshfruit',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19),
        ),
        migrations.AlterField(
            model_name='icedlemontea',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9),
        ),
        migrations.AlterField(
            model_name='icedlemontea',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19),
        ),
        migrations.AlterField(
            model_name='icedmilktea',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9),
        ),
        migrations.AlterField(
            model_name='icedmilktea',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19),
        ),
    ]
