# Generated by Django 3.0.8 on 2020-08-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200803_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotfreshfruit',
            name='product',
        ),
        migrations.RemoveField(
            model_name='hotfreshfruit',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='hotfreshfruit',
            name='toppings',
        ),
    ]
