# Generated by Django 3.0.8 on 2020-08-04 18:49

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20200804_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotfreshfruit',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AddField(
            model_name='hotfreshfruit',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='hotfreshfruit',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='hotcheesefoam',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='hotcheesefoam',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='hotcheesefoam',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='hotlemontea',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='hotlemontea',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='hotlemontea',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='hotmilktea',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='hotmilktea',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='hotmilktea',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='icedcheesefoam',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='icedcheesefoam',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='icedcheesefoam',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='icedfreshfruit',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='icedfreshfruit',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='icedfreshfruit',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='icedlemontea',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='icedlemontea',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='icedlemontea',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='icedmilktea',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='icedmilktea',
            name='sugar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'No Sugar'), ('b', '30% Sugar'), ('c', '50% Sugar'), ('d', '80% Sugar'), ('e', '100% Sugar')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='icedmilktea',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19, null=True),
        ),
    ]
