# Generated by Django 3.0.8 on 2020-08-04 20:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20200804_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotcheesefoam',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='hotfreshfruit',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='hotlemontea',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='hotmilktea',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='icedcheesefoam',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='icedfreshfruit',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='icedlemontea',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='icedmilktea',
            name='sugar',
        ),
        migrations.AlterField(
            model_name='hotfreshfruit',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], default=(('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')), max_length=19, null=True),
        ),
    ]
