# Generated by Django 3.0.8 on 2020-08-04 20:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200804_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotfreshfruit',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl'), ('b', 'Grass Jelly'), ('c', 'Red Beans'), ('d', 'Coconut Jelly'), ('e', 'Pudding'), ('f', 'Agar Ball'), ('h', 'Aloe'), ('i', 'Popping Boba'), ('j', 'Oreo'), ('k', 'Cheese Foam')], max_length=19, null=True),
        ),
    ]
