# Generated by Django 3.0.8 on 2020-08-04 23:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20200804_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotcheesefoam',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl ($0.50)'), ('b', 'Red Beans ($0.50)'), ('c', 'Coconut Jelly ($0.50)'), ('d', 'Pudding ($0.50)'), ('e', 'Agar Ball ($0.75)'), ('f', 'Aloe ($0.75)'), ('g', 'Popping Boba ($0.75)'), ('h', 'Oreo ($1.00)'), ('i', 'Cheese Foam ($1.00)')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='hotfreshfruit',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl ($0.50)'), ('b', 'Red Beans ($0.50)'), ('c', 'Coconut Jelly ($0.50)'), ('d', 'Pudding ($0.50)'), ('e', 'Agar Ball ($0.75)'), ('f', 'Aloe ($0.75)'), ('g', 'Popping Boba ($0.75)'), ('h', 'Oreo ($1.00)'), ('i', 'Cheese Foam ($1.00)')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='hotlemontea',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl ($0.50)'), ('b', 'Red Beans ($0.50)'), ('c', 'Coconut Jelly ($0.50)'), ('d', 'Pudding ($0.50)'), ('e', 'Agar Ball ($0.75)'), ('f', 'Aloe ($0.75)'), ('g', 'Popping Boba ($0.75)'), ('h', 'Oreo ($1.00)'), ('i', 'Cheese Foam ($1.00)')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='hotmilktea',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl ($0.50)'), ('b', 'Red Beans ($0.50)'), ('c', 'Coconut Jelly ($0.50)'), ('d', 'Pudding ($0.50)'), ('e', 'Agar Ball ($0.75)'), ('f', 'Aloe ($0.75)'), ('g', 'Popping Boba ($0.75)'), ('h', 'Oreo ($1.00)'), ('i', 'Cheese Foam ($1.00)')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='icedcheesefoam',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl ($0.50)'), ('b', 'Red Beans ($0.50)'), ('c', 'Coconut Jelly ($0.50)'), ('d', 'Pudding ($0.50)'), ('e', 'Agar Ball ($0.75)'), ('f', 'Aloe ($0.75)'), ('g', 'Popping Boba ($0.75)'), ('h', 'Oreo ($1.00)'), ('i', 'Cheese Foam ($1.00)')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='icedfreshfruit',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl ($0.50)'), ('b', 'Red Beans ($0.50)'), ('c', 'Coconut Jelly ($0.50)'), ('d', 'Pudding ($0.50)'), ('e', 'Agar Ball ($0.75)'), ('f', 'Aloe ($0.75)'), ('g', 'Popping Boba ($0.75)'), ('h', 'Oreo ($1.00)'), ('i', 'Cheese Foam ($1.00)')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='icedlemontea',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl ($0.50)'), ('b', 'Red Beans ($0.50)'), ('c', 'Coconut Jelly ($0.50)'), ('d', 'Pudding ($0.50)'), ('e', 'Agar Ball ($0.75)'), ('f', 'Aloe ($0.75)'), ('g', 'Popping Boba ($0.75)'), ('h', 'Oreo ($1.00)'), ('i', 'Cheese Foam ($1.00)')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='icedmilktea',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'Pearl ($0.50)'), ('b', 'Red Beans ($0.50)'), ('c', 'Coconut Jelly ($0.50)'), ('d', 'Pudding ($0.50)'), ('e', 'Agar Ball ($0.75)'), ('f', 'Aloe ($0.75)'), ('g', 'Popping Boba ($0.75)'), ('h', 'Oreo ($1.00)'), ('i', 'Cheese Foam ($1.00)')], max_length=17, null=True),
        ),
    ]
