# Generated by Django 3.0.8 on 2020-08-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20200804_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotFreshFruit',
            new_name='FreshFruit',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='bbt.png', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='IcedFreshFruit',
        ),
    ]
