# Generated by Django 3.0.8 on 2020-08-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20200805_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isHot',
        ),
        migrations.AddField(
            model_name='cheesefoam',
            name='isHot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freshfruit',
            name='isHot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lemontea',
            name='isHot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milktea',
            name='isHot',
            field=models.BooleanField(default=False),
        ),
    ]
