# Generated by Django 3.0.8 on 2020-08-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_auto_20200805_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=99)),
                ('image', models.ImageField(blank=True, default='bbt.png', null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='cheesefoam',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='freshfruit',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='lemontea',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='milktea',
            name='toppings',
        ),
        migrations.AddField(
            model_name='cheesefoam',
            name='toppings',
            field=models.ManyToManyField(to='menu.Topping'),
        ),
        migrations.AddField(
            model_name='freshfruit',
            name='toppings',
            field=models.ManyToManyField(to='menu.Topping'),
        ),
        migrations.AddField(
            model_name='lemontea',
            name='toppings',
            field=models.ManyToManyField(to='menu.Topping'),
        ),
        migrations.AddField(
            model_name='milktea',
            name='toppings',
            field=models.ManyToManyField(to='menu.Topping'),
        ),
    ]
