runtime: python37
env: standard
instance_class: F4
handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 4
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}