version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    # volumes:
    #   - ./app/:/usr/src/app/
    ports:
      - 80:80
    # env_file:
    #   - ./.env.dev