<<<<<<< HEAD
# Generated by Django 3.1 on 2020-08-29 05:01
=======
# Generated by Django 3.1 on 2020-08-28 19:49
>>>>>>> 668d4e44acf3333028eee3b1f81f8d2be33889db

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=5000)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
