# Generated by Django 3.0.8 on 2020-08-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
